{% set version = "4.3.18" %}

package:
  name: chaospy
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: 7b5f1401935dac616f362941e216b96636edb47cb0fe4d85901a88d4f219e13b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - poetry
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - scikit-learn
    - numpoly ==1.0.6

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - pytest-runner
  commands:
    - py.test

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
