{% set version = "4.2.7" %}

package:
  name: chaospy
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: 2685506a44433f7c52930797f0bf0293cb362723916a005a2e322cfa1823971e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip
  run:
    - python >=3.7
    - networkx
    - numpy >=1.20
    - scipy
    - scikit-learn
    - numpoly >=1.2.5

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - pytest-runner
  commands:
    - py.test

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
    - gallardoalba