{% set version = "3.3.9" %}

package:
  name: chaospy
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: 75c58bdbd3181d0e87eb8077680d20aff9f0ef954fe9b58c233005d386187c7b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - poetry
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - numpoly ==1.0.6

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - pytest-runner
    - python {{ python_min }}
  commands:
    - py.test

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
