{% set name = "chaospy" %}
{% set version = "4.3.19" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: b6a646ab7b2fb2a5575c69eb61c941113d8dfd8af9516d6362529f2315bdbc73

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - poetry
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scipy
    - scikit-learn
    - numpoly >=1.2.12

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest-runner
  commands:
    - pip check

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
