travis:
  secure:
    BINSTAR_TOKEN: nmhredmQI1R1VdUIQX9bglIk8vhLEvVAdNAa7MbXR3E4uONPs+D3pwQWLgC0fMd89WlrFt/e4tIkpnsNTub2LyGXP7Xa//MKR37TExxfNduDcnNnm4eRGCVYoVmvCzBRuiRPk/78M+BfOApAcWc7pCtdt7Hy0qmxh4vV+Y4bjWPj/UzcjD3OOzRkL5+V66OAcNaNGnLZnlYGiGYo6Zo2TWfe4U9VCl/TbmiuqlyqhPodB5I3F577ocCFVFx1oaVZIzIY9YV8ougAwBRDsDv77ouG1KSrNlPdIKDhVGR+n2cf5GmxRIZFqGIYWmHeDj4QjsBwXhUOLLX5oZbm37HLef5wiEfh5U9jZJkc+goAx+k0Zxt5/cyuN8+az+JvTFVyXEyeLCurtyYv7MZ6LYOFUkQHi4f+xxeqNlvo1ROm4kG3QdRGrsOSnkZ+t7glOa5UUOGm5CDwSpyL/A1I3+ykyoQRGmchVV7giAdyRp8Ye/aD4NyUP+DmjRsci++TuwMaUBbDUB62nF1XrC3jQ6jLx2tvPdcKqdfyUXOjT3O12WgFwKgsCWNTD4lzYNlDXK+N2MxxnK915GbXoY89MstJqLUljtBpUYY1OuiZdNjQcQta00Zsb/oOIlY5qLqIKDJk+9K8jt+gQk6hPu/uEHGa5CvbBATikIuQz8J2E30z3KQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
